import { getApiErrorCode } from "@/services/common/responseParser";

export const LANGUAGE_LEARNING_ERROR_CODES = {
    SETTING_INVALID: "LANGUAGE_LEARNING_SETTING_INVALID",
    SETTING_NOT_CONFIGURED: "LANGUAGE_LEARNING_SETTING_NOT_CONFIGURED",
    KEYWORD_DUPLICATED: "LANGUAGE_LEARNING_KEYWORD_DUPLICATED",
    LEVEL_TEST_REQUIRED: "LANGUAGE_LEARNING_LEVEL_TEST_REQUIRED",
    LEVEL_TEST_INVALID_STATE: "LANGUAGE_LEARNING_LEVEL_TEST_INVALID_STATE",
    DAILY_SET_GENERATING: "LANGUAGE_LEARNING_DAILY_SET_GENERATING",
    DAILY_SET_GENERATION_FAILED: "LANGUAGE_LEARNING_DAILY_SET_GENERATION_FAILED",
    REGENERATION_LIMIT: "LANGUAGE_LEARNING_REGENERATION_LIMIT",
    ANSWER_NOT_ALLOWED: "LANGUAGE_LEARNING_ANSWER_NOT_ALLOWED",
    REVIEW_EXPIRED: "LANGUAGE_LEARNING_REVIEW_EXPIRED",
    EVALUATION_FAILED: "LANGUAGE_LEARNING_EVALUATION_FAILED",
} as const;

export function getLanguageLearningErrorCode(error: unknown) {
    return getApiErrorCode(error);
}
